export const tabbarItems = [];

export const DATA = [
  {
    id: 547775,
    title: 'Creamy Avocado Pasta',
    image: 'https://spoonacular.com/recipeImages/547775-312x231.jpg',
    imageType: 'jpg',
    type: 'Pasta',
  },
  {
    id: 818941,
    title: 'Avocado Toast with Eggs, Spinach, and Tomatoes',
    image: 'https://spoonacular.com/recipeImages/818941-312x231.jpg',
    imageType: 'jpg',
    type: 'Avocado',
  },
  {
    id: 495111,
    title: 'Citrus Sesame Kale',
    image: 'https://spoonacular.com/recipeImages/495111-312x231.jpg',
    imageType: 'jpg',
    type: 'Cabbage',
  },
  {
    id: 689502,
    title: 'Melt In Your Mouth Kale Salad',
    image: 'https://spoonacular.com/recipeImages/689502-312x231.jpg',
    imageType: 'jpg',
    type: 'Salad',
  },
  {
    id: 582897,
    title: 'Mexican Salad with Lime Dressing',
    image: 'https://spoonacular.com/recipeImages/582897-312x231.jpg',
    imageType: 'jpg',
    type: 'Salad',
  },
  {
    id: 777037,
    title: 'Weekly Meal Plan #17',
    image: 'https://spoonacular.com/recipeImages/777037-312x231.jpg',
    imageType: 'jpg',
    type: 'Other',
  },
  {
    id: 801710,
    title: 'Matcha Green Tea and Pineapple Smoothie',
    image: 'https://spoonacular.com/recipeImages/801710-312x231.jpg',
    imageType: 'jpg',
    type: 'Smoothie',
  },
  {
    id: 547776,
    title: 'Creamy Avocado Pasta',
    image: 'https://spoonacular.com/recipeImages/547775-312x231.jpg',
    imageType: 'jpg',
    type: 'Pasta',
  },
  {
    id: 818942,
    title: 'Avocado Toast with Eggs, Spinach, and Tomatoes',
    image: 'https://spoonacular.com/recipeImages/818941-312x231.jpg',
    imageType: 'jpg',
    type: 'Avocado',
  },
  {
    id: 495112,
    title: 'Citrus Sesame Kale',
    image: 'https://spoonacular.com/recipeImages/495111-312x231.jpg',
    imageType: 'jpg',
    type: 'Cabbage',
  },
  {
    id: 689503,
    title: 'Melt In Your Mouth Kale Salad',
    image: 'https://spoonacular.com/recipeImages/689502-312x231.jpg',
    imageType: 'jpg',
    type: 'Salad',
  },
  {
    id: 582898,
    title: 'Mexican Salad with Lime Dressing',
    image: 'https://spoonacular.com/recipeImages/582897-312x231.jpg',
    imageType: 'jpg',
    type: 'Salad',
  },
  {
    id: 777038,
    title: 'Weekly Meal Plan #17',
    image: 'https://spoonacular.com/recipeImages/777037-312x231.jpg',
    imageType: 'jpg',
    type: 'Other',
  },
  {
    id: 801711,
    title: 'Matcha Green Tea and Pineapple Smoothie',
    image: 'https://spoonacular.com/recipeImages/801710-312x231.jpg',
    imageType: 'jpg',
    type: 'Smoothie',
  },
];
